### ISSUE TITLE
Error: Unknown authentication strategy simple in /

### ISSUE THREAD

**Issue by dciccale** [johnbrett/hapi-auth-bearer-token#104]
Copy & paste the example on the README and run it with node

Hapi v15.1.1

apparently now register truly runs async, so trying to register routes before it finishes to register the auth strategy fails, could you update your example?

**Comment by johnbrett** [comment]
Excellent spot @dciccale - will do.

**Comment by dciccale** [comment]
thanks!

**Comment by AdriVanHoudt** [comment]
fixed by https://github.com/johnbrett/hapi-auth-bearer-token/commit/7d0102339ba47d0377b25bc0239714c0c1034208
