### ISSUE TITLE
enable new greenkeeper bot

### ISSUE THREAD

**Issue by AdriVanHoudt** [johnbrett/hapi-auth-bearer-token#113]
Seeing the amount of PR's from greenkeeper it would make sense to enable the new bot (https://github.com/integration/greenkeeper) which ammends 1 PR per module update
See https://github.com/Salesflare/hapi-csv/pull/11 for example

@johnbrett since you are the owner you'll have to do it ^^

**Comment by johnbrett** [comment]
I was on vacation the last while, will update all these PR's this week @AdriVanHoudt, thanks for the good work!

**Comment by AdriVanHoudt** [comment]
@johnbrett ah I see, hope you had a nice vacation 🏖 😎 
I could merge them myself nextime as well if you'd like

**Comment by johnbrett** [comment]
Sorry for delay on this - and thanks for pointing out the new greenkeeper bot! It's been added now!
