### ISSUE TITLE
Chaining multiple queryToken strategies does not work

### ISSUE THREAD

**Issue by AdriVanHoudt** [johnbrett/hapi-auth-bearer-token#124]
Since the query token get's deleted here: https://github.com/johnbrett/hapi-auth-bearer-token/blob/master/lib/index.js#L55 the next strategy looking for it simply can't find it.
Not sure how to fix this but I think the easiest is to delete it only just before a successful auth here https://github.com/johnbrett/hapi-auth-bearer-token/blob/master/lib/index.js#L94

**Comment by johnbrett** [comment]
I'll take a look at this on Monday @AdriVanHoudt! Sorry for delay, I'm way behind on OSS, thanks for opening this 👍

**Comment by AdriVanHoudt** [comment]
np!

**Comment by johnbrett** [comment]
closed via https://github.com/johnbrett/hapi-auth-bearer-token/pull/156
