### ISSUE TITLE
can we skip some routes from authentication

### ISSUE THREAD

**Issue by 1010systems** [johnbrett/hapi-auth-bearer-token#127]
Hello,

we are using AuthBearer plugin for authentication. can we skip some routes from the authetication?
something like 
```
auth{
strategy: ""
} 
```

or 
`auth : false`

Thanks in advance.

**Comment by johnbrett** [comment]
Yes on the route definition, you can set auth to false, so authentication won't apply to that route.

Example: https://github.com/johnbrett/Getting-Started-with-hapi.js/blob/master/Chapter%205%20-%20Authentication%20%26%20Authorization/example%201%20-%20hapi-auth-basic/lib/routes.js#L5-L13.
