### ISSUE TITLE
Remove .vscode and add changelog

### ISSUE THREAD

**Issue by RicardoGeek** [johnbrett/hapi-auth-bearer-token#135]
Remove .vscode from versioning and add it go .gitignore
Add a changelog to the project :)

**Comment by AdriVanHoudt** [comment]
A PR for removing the .vscode folder is welcome (unless @johnbrett has an actual reason to have it in the repo?) 
The changelog is up to him as well ^^

**Comment by johnbrett** [comment]
Hi @RicardoGeek,

My reasoning behind the .vscode, I leave that in my projects so anyone who wants to debug tests have the option to do so on opening of the repo easily, just open project in vscode, set a breakpoint, run. No need to configure launch files etc. I see no real downsides of this being there - but happy to listen any complaints or reasoning why it should be removed. 

I could see reasoning to adding it to an npm ignore, and would accept that a PR on that though.

On the changelog, I think as this module has so few changes, and no expected new features on the roadmap it would be unnecessary overhead. 

Thanks for the early reply also @AdriVanHoudt 👍
