### ISSUE TITLE
v6 Release Notes

### ISSUE THREAD

**Issue by johnbrett** [johnbrett/hapi-auth-bearer-token#146]
`hapi-auth-bearer-token` v6 Drops support for hapi < v17 and Node < 8, due to the nature of the hapi v17 rewrite: https://github.com/hapijs/hapi/issues/3658.

### breaking changes:
- `validateFunc` is renamed to `validate`. The Func suffix was an old convention to signify a function to be passed in here. This much cleaner and less intimidating to new users.
- `unauthorizedFunc` is renamed to `unauthorized`. Same reasoning as `validateFunc`.
- `validate` function signature `function (token)` becomes `[async] function(request, token, h)`. Previously `request` had to be accessed via `this`, and only when the `function` keyword was used, as to avoid making a breaking change. This was inconsistent and confusing and has been remedied in this release.

**Please note**: as part of changes with in `hapi` v17, `server.auth.default('simple');` must now be used when setting a default auth strategy. Default strategies can no longer be set when calling `server.auth.strategy`. Please be careful with this.

**Comment by wy193777** [comment]
Didn't mention the plugin expect validateFunc have a callback as the last parameter and need to be called with signature 
```
callback(isValid, credentials, artifacts) 
```
before 6.0.

**Comment by johnbrett** [comment]
Hi @wy193777 is this a question or any observation? I'm not sure I understand what you are looking for.

The following is a screenshot of the README before 6.0, where `validateFunc` and the callback signature are underlined:

![image](https://user-images.githubusercontent.com/4015939/34878327-b6b18c74-f7a1-11e7-91d0-53aad1c86ed2.png)

https://github.com/johnbrett/hapi-auth-bearer-token/blob/8da70ac735fb4f2ba47e0958e493e90804e6d394/README.md

**Comment by wy193777** [comment]
I mean put this difference here or have a link to the 5.x.x document on README.md would be better. Find the right commit from commit list isn't a very good experience.

**Comment by johnbrett** [comment]
Updated the release notes, thanks for pointing it out.

**Comment by daguiheso** [comment]
Good afternoon

I would like to know how I should create a bearer token?
