### ISSUE TITLE
Undefined token passed to validate function

### ISSUE THREAD

**Issue by randyxli** [johnbrett/hapi-auth-bearer-token#147]
In version 4.3.1 with default options, I noticed that when the `Authorization` header is just `Bearer`, the `token` parameter that is passed to the `validate` function is `undefined`. Looking through the code, it seems to me that this is the case for current master as well. Although this behavior is reasonable, I wonder if it would be more appropriate to reply with `Boom.unauthorized`? I don't see how not having a token should ever result in a successful authentication, so it would be convenient for the middleware to handle that case.

**Comment by johnbrett** [comment]
Nice spot, and agreed. Will update this.

**Comment by johnbrett** [comment]
This is fixed in v 6.0.1: https://github.com/johnbrett/hapi-auth-bearer-token/commit/526edcf8fb6b692adb335d0f81681962358506b7#diff-6d186b954a58d5bb740f73d84fe39073R74 Thanks for creating the issue 👍

**Comment by randyxli** [comment]
No problem, thanks for the quick fix!
