### ISSUE TITLE
The validation method is crashing  when calling from mongoDb

### ISSUE THREAD

**Issue by ramonDecoda** [johnbrett/hapi-auth-bearer-token#15]
Sorry to bother am new Hapijs and am trying your plugin using mongo as back end when i look for the user using User.findById in the validation method i  get this exception:tried everything but here i am.

    Debug: internal, implementation, error 
    TypeError: Property '_next' of object function (err, response, data) {

        reply._data = data;                 // Held for later
        return reply.response(err !== null && err !== undefined ? err : response);
    } is not a function
    at Function.internals.continue (E:\newCode\webApps\node_modules\hapi\lib\reply.js:102:10)
    at E:\newCode\webApps\node_modules\hapi-auth-bearer-token\lib\index.js:65:42
    at Promise.<anonymous> (E:\newCode\webApps\app\utils\autho.js:18:32)
    at Promise.<anonymous> (E:\newCode\webApps\node_modules\mongoose\node_modules\mpromise\lib\promise.js:177:8)
    at Promise.emit (events.js:95:17)
    at Promise.emit (E:\newCode\webApps\node_modules\mongoose\node_modules\mpromise\lib\promise.js:84:38)
    at Promise.fulfill (E:\newCode\webApps\node_modules\mongoose\node_modules\mpromise\lib\promise.js:97:20)
    at E:\newCode\webApps\node_modules\mongoose\lib\query.js:1394:13
    at model.Document.init (E:\newCode\webApps\node_modules\mongoose\lib\document.js:250:11)
    at completeOne (E:\newCode\webApps\node_modules\mongoose\lib\query.js:1392:10)

This the method used in the validation

```javascript
    function (token, callback) {
    if (token) {
        try {
            var decodedToken = jwt.decode(token, config.secretToken);
            if (decodedToken.exp && decodedToken.exp <= Date.now()) {
                return callback(null, false);
            }
            User.findById(decodedToken.iss, '_id uName',
                function (err, users) {
                    if (!err) {
                        return callback(null, true, users);
                    }
                });

        } catch (err) {
            return callback(null, false);
        }
    }
    return callback(null, false);
    }

Thanks

**Comment by johnbrett** [comment]
Hi @ramonDecoda, I need a bit more information to help with debugging. What versions of Hapi and Hapi-auth-bearer-token are you using?

Also, can you paste in the full method code? If the code is on github I could take a look at it either?

Is User.findById a promise that you are treating as a callback also ?

**Comment by ramonDecoda** [comment]
I don't have the source on Git but i will upload part of the  code.Everything works Am getting the token and decryption it in the validation method but everything goes wrong when returning the user object from the DB but.

Am use using "hapi-auth-bearer-token": "^3.1.0",

am registering the plugin at the creation of service
```javascript
'use strict';

var Hapi = require('hapi'),
    autho = require('../app/utils/autho');

module.exports = function (config) {
    var server = new Hapi.Server();

    //Set app port
    server.connection({port: config.port});

     //Set app auth
    server.register(require('hapi-auth-bearer-token'), function (err) {
        server.auth.strategy('simple', 'bearer-access-token', {
            allowQueryToken: false,
            allowMultipleHeaders: false,
            accessTokenName: 'access_token',
            validateFunc: autho.validate
        });
    });

    //Register app routes
    server.register({
           register: require('hapi-route-auto-reg'),
           options: {
               directory: './app/routes/'
           }
       }, function (err) {
           if (err) {
               console.log('Server failed to load routes');
               throw err;
           }
       });

    return server;
};
```
this is the class autho were i placed validate method config has the token key and DB connection 

```javascript
'use strict';

var User = require('../models/user_model').User;
var config = require('../../config/config'),
    jwt = require('jsonwebtoken');

module.exports.validate = function (token, callback) {
    if (token) {
        try {
            var decodedToken = jwt.decode(token, config.secretToken);
            if (decodedToken.exp && decodedToken.exp <= Date.now()) {
                return callback(null, false);
            }
            User.findById(decodedToken.iss, '_id uName roles enabled',
                function (err, users) {
                    if (!err) {
                        return callback(null, true, users);
                    }
                });
        } catch (err) {
            console.log(err);
            return callback(null, false);
        }
    }

    return callback(null, false);
};
```
this is the User model schema i even tried using the method findByToken but the same error
```javascript
'use strict';

var mongoose = require('mongoose'),
    crypto = require('crypto');

var UserSchema = new mongoose.Schema({
    uName: {
        type: String,
        trim: true,
        unique: true,
        required: 'User name is required'
    },
    email: {
        type: String,
        trim: true,
        unique: true
    },
    pass: {
        type: String,
        required: 'Password is required'
    },
    salt: {
        type: String
    },
    roles: {
        type: [
            {
                type: String,
                enum: ['user', 'manager', 'admin']
            }
        ],
        default: ['user']
    },
    enabled: {
        type: Boolean,
        default: false
    }
});

UserSchema.methods.hashPassword = function (password) {
    if (this.salt && password) {
        return crypto.pbkdf2Sync(password, this.salt, 10000, 64).toString('base64');
    } else {
        return password;
    }
};

UserSchema.pre('save', function (next) {
    if (this.pass && this.pass.length > 8) {
        this.salt = new Buffer(crypto.randomBytes(16).toString('base64'), 'base64');
        this.pass = this.hashPassword(this.pass);
    }
    next();
});

UserSchema.methods.authenticate = function (password) {
    return this.pass === this.hashPassword(password);
};

UserSchema.statics.findByToken = function (userId, cb) {
    this.findById(userId, '_id uName roles enabled', cb);
};

exports.User = mongoose.model('User', UserSchema, 'Users');
```

Sorry for the trouble and thanks again

**Comment by johnbrett** [comment]
No worries about the trouble. It only gives me a better understanding of Hapi :)

So it looks to me like you're using the hapi-auth-bearer-token just fine. Can you put a console log before each callback and see which one is being called and with what? 

I've two theories:
1. Either the users object returned is a promise causing the above error // We'll catch this by console logging the user object
2. Your requests are being authenticated correctly, and it's something further in the request lifecycle that is causing the problem. // Can you put a console log inside the handler or any prehandlers to see if it is being reached?

**Comment by ramonDecoda** [comment]
Found the bug it was the last  return in the validation function had to fix it if else and it worked thanks
i forget its js.

```javascript

use strict';

var User = require('../models/user_model').User;
var config = require('../../config/config'),
    jwt = require('jsonwebtoken');

module.exports = function (server) {
    var validate = function (token, callback) {
        if (token) {
            var decodedToken = jwt.decode(token, config.secretToken);
            User.findByToken(decodedToken.iss, function (err, user) {
                if (user) {
                    return callback(null, true, user);
                } else {
                    return callback(null, false);
                }
            });
        }else{
            return callback(null, false);
        }
    };

    server.register(require('hapi-auth-bearer-token'), function (err) {
        if (err) {
            console.log('Server failed to set security');
            throw err;
        }
        server.auth.strategy('simple', 'bearer-access-token', {
            allowQueryToken: false,
            allowMultipleHeaders: false,
            accessTokenName: 'access_token',
            validateFunc:validate
        });
    });
};


```

**Comment by johnbrett** [comment]
Happy to hear you got it sorted, any further problems don't hesitate to get in touch.
