### ISSUE TITLE
Double validation error

### ISSUE THREAD

**Issue by Pyy-admin** [johnbrett/hapi-auth-bearer-token#161]
auth: {
       strategies: ['admin','user']
 },
The problem I met was the first admin to verify, but the second user was invalid.

**Comment by johnbrett** [comment]
I need more details to be able to offer any advice on this, are you sure this is an issue with this library or how hapi resolves multiple strategies? I'll close this for now, but please re-open if you have more details to add.

Apologies for delay in getting back to you on this.
