### ISSUE TITLE
Add support for authorization payload

### ISSUE THREAD

**Issue by JakubJagoda** [johnbrett/hapi-auth-bearer-token#17]
In hapi authorization scheme is expected to return `authenticate` function, however the data stored in payload is then not available to the user. But the scheme can also return `payload` function which then can be used to use payload data during authorization.

I needed this functionality in one of the projects, therefore I already wrote the necessary code: https://github.com/johnbrett/hapi-auth-bearer-token/pull/18
(however I didn't dig into the plugin structure, so maybe this can be (and should) written in other fashion)

**Comment by johnbrett** [comment]
Hey @JakubJagoda, thanks for contributing this. This module always maintains 100% test coverage - can you get test coverage back to 100% to go with this PR? `npm test` will give you all the coverage info you need. I can any refactoring needed after. Let me know if you need any help writing tests.

**Comment by JakubJagoda** [comment]
Sure, @johnbrett, I'll take care of the tests today's evening (in a few hours)

**Comment by johnbrett** [comment]
Hi @JakubJagoda, sorry for late reply - I was away on holidays. Do you need a hand with writing the tests?

**Comment by JakubJagoda** [comment]
hi @johnbrett! No, I don't need a hand, I'm familiar with jasmine test specs. I have been just _deadly_ busy recently, so had no time to write them. I'll do this as soon as I have some free time (hopefully soon).

**Comment by johnbrett** [comment]
No worries @JakubJagoda, I know the feeling :)

**Comment by johnbrett** [comment]
Hi @JakubJagoda, I don't like leaving issues open for a long period of time so will close this due to inactivity - if you want to continue working on this or anyone else would like this feature added, I encourage you to re-open and we can discuss.
