### ISSUE TITLE
Update & bump 🏷

### ISSUE THREAD

**Issue by bricss** [johnbrett/hapi-auth-bearer-token#200]
Update & bump is badly needed to comport with newest hapi ecosystem. 🔩

**Comment by johnbrett** [comment]
Hey sorry, swamped at the moment. Will hopefully get to it this week, but PR's always welcome!

**Comment by johnbrett** [comment]
6.1.4 is out: https://github.com/johnbrett/hapi-auth-bearer-token/commit/3345520c3568a212a668d0fc37397c1354561431

Let me know if anything further needed!
