### ISSUE TITLE
Library does not work with the new independent "joi" library which has now split from @hapi/joi

### ISSUE THREAD

**Issue by eric-swann-q2** [johnbrett/hapi-auth-bearer-token#209]
Library does not work with the new independent "joi" library which has now split from @hapi/joi.

This lib has dependencies on @hapi/joi and @hapi/boom.  
The @hapi/joi dependency in particular causes a collision when using the new joi library as joi detects two versions and throws an exception.

Solution: Instead set both of the libraries as peer dependencies for maximum flexibility and reference "joi" as opposed to "@hapi/joi" for future versions.

**Comment by johnbrett** [comment]
Resolved by https://github.com/johnbrett/hapi-auth-bearer-token/pull/210

Released in v8.0.0.
