### ISSUE TITLE
version 8.0.0

### ISSUE THREAD

**Issue by AdriVanHoudt** [johnbrett/hapi-auth-bearer-token#211]
Hi,

I'm seeing a new version (8.0.0) on npm but I don't see this on this repo?
Was there a push forgotten or something?
Just want to make sure v8 is a legit version :D

**Comment by johnbrett** [comment]
Just pushed there, sorry 😅

**Comment by AdriVanHoudt** [comment]
haha no worries ✨

**Comment by johnbrett** [comment]
Thanks for this Adri!
