### ISSUE TITLE
Does this support try or optional mode?

### ISSUE THREAD

**Issue by nelsonic** [johnbrett/hapi-auth-bearer-token#33]
Hi @johnbrett 
can you please clarify if this plugin supports the `try` or `optional` modes?
Tried searching in your docs and [tests](https://github.com/johnbrett/hapi-auth-bearer-token/blob/589749b8b3fc96ed1fc47dd2e73c32ab0d34e6d4/test/index.js) but did not find any reference to either.
Thanks.

**Comment by johnbrett** [comment]
Hi @nelsonic - apologies only seeing this issue now. Are you referring to the server auth strategy options: http://hapijs.com/api#serverauthstrategyname-scheme-mode-options

Test for these would be covered in hapi's API tests, as it's how hapi interprets and uses the authentication scheme.

Are you having trouble finding an example using these scheme with try or optional modes?
