### ISSUE TITLE
mutliple headers and tokentype

### ISSUE THREAD

**Issue by PetrSnobelt** [johnbrett/hapi-auth-bearer-token#54]
I think there should be used tokenType in regexp in this line, instead of hardcoded Bearer string
https://github.com/johnbrett/hapi-auth-bearer-token/blob/master/lib/index.js#L49

also will be great if it works without tokentype by specifiing tokenType = ''

**Comment by johnbrett** [comment]
Hi @PetrSnobelt. This is specifically a bearer authentication scheme, thus the hardcoded string. 

Would something like this may suit your needs better: https://github.com/atomantic/hapi-auth-header?

**Comment by PetrSnobelt** [comment]
OK, hapi-auth-header can be usefull for me, but in fact it looks like I move to jwt tokens...

I think that if you have soapToken options it should respect this settings. But it's up to you, you can close this. Thank you for hapi auth header link.

**Comment by johnbrett** [comment]
Thanks for the feedback @PetrSnobelt. This particular module aims to be compliant with how bearer token usage is defined here in RFC6750: https://tools.ietf.org/html/rfc6750#page-5

Note in the request header field the specific "bearer" string. I think for your use case a more general authentication scheme like jwt or the one I linked will suit better.
