### ISSUE TITLE
Expose token

### ISSUE THREAD

**Issue by AdriVanHoudt** [johnbrett/hapi-auth-bearer-token#87]
Is there a way to expose the token? In auth bearer simple I just added it to the credentials (https://github.com/Salesflare/hapi-auth-bearer-simple/blob/master/lib/index.js#L31) but there is probably a safer way :P

**Comment by johnbrett** [comment]
In your `validateFunc` can you pass to token to the `artifacts` argument, like in this test? https://github.com/johnbrett/hapi-auth-bearer-token/blob/master/test/index.js#L50-L53

**Comment by AdriVanHoudt** [comment]
hmm I read about it but did not fully understood the meaning of artifacts. If this is just a container that is not used elsewhere then that works for me.

**Comment by johnbrett** [comment]
Yeah it's just there to contain extra auth information, so sounds like it would be perfect for this use case. If it's somehow not, let me know though!

**Comment by koresar** [comment]
Hey, great to see we're not the only who needed the artefacts! :)
@AdriVanHoudt you might find this PR relevant: https://github.com/johnbrett/hapi-auth-bearer-token/pull/76
It's got links and quotes form the docs.

**Comment by AdriVanHoudt** [comment]
@koresar thanks for the link! really interesting!
