### ISSUE TITLE
Strategy chaining

### ISSUE THREAD

**Issue by AdriVanHoudt** [johnbrett/hapi-auth-bearer-token#88]
Currently it is not possible to chain strategies. 
hapi docs: ` If the err does not include a message but does include a scheme name (e.g. Boom.unauthorized(null, 'Custom')), additional strategies will be attempted in order of preference.` (under https://github.com/hapijs/hapi/blob/master/API.md#serverauthschemename-scheme)
And since on `!isValid` there is an unauthorized error with message, hapi will not try other strategies (https://github.com/johnbrett/hapi-auth-bearer-token/blob/508d37177b335ca98fc69834ce85770e55896386/lib/index.js#L74)

Am I correct or am I just doing something wrong?

(background: as you may now I wrote https://github.com/Salesflare/hapi-auth-bearer-simple but now we do have a need for query param functionallity and at that point the gap seems to close to have 2 versions of this scheme type ;) )

**Comment by johnbrett** [comment]
This must be new, or I certainly haven't seen it before! `"If the err does not include a message but does include a scheme name (e.g. Boom.unauthorized(null, 'Custom')), additional strategies will be attempted in order of preference."`

By my understanding of this you're correct in the assumption here. Are you hoping to do chaining here? What's your use case, maybe I can help? :)

**Comment by AdriVanHoudt** [comment]
Yes we are doing chaining, we have a separate strategy for private and public usage of certain routes of our api. We try private first then public.

I have quickly updated auth-simple (out of business needs) but I am in favor of just one to rule them all :D

**Comment by johnbrett** [comment]
Happy to give you write access on this if you've any changes you'd like to make? http://openopensource.org/ FTW ;)

**Comment by AdriVanHoudt** [comment]
that would be cool, it would involve removing the error message and exposing the token in artifacts by default I guess

**Comment by johnbrett** [comment]
can you not pass in the token in the application code to artifacts? e.g.

````javascript
server.auth.strategy('simple', 'bearer-access-token', {
        allowQueryToken: true,              // optional, true by default
        allowMultipleHeaders: false,        // optional, false by default
        accessTokenName: 'access_token',    // optional, 'access_token' by default
        validateFunc: function (token, callback) {

            // verify login token e.g. user = User.findById(token);

            if (user) {
                // now user and token are accessible from  request.auth.credentials.user && request.auth.artifacts.token
                return callback(null, true, { user: user }, { token: token });
            }

            return callback(null, false, { token: token }, { artifact1: 'an artifact' });
        }
    });
````

**Comment by AdriVanHoudt** [comment]
I could but it would be easier if the plugin did it by default

**Comment by AdriVanHoudt** [comment]
hmm not sure maybe @koresar knows since he has clearly used it before

**Comment by koresar** [comment]
We do not use chaining. I would not recommend using that Hapi feature either. You would rely on some deeper Hapi mechanism - breaking change may happen there. Or you would need to change the chaining mechanism slightly (e.g. second auth schema depends on the artefacts of the first auth schema). Etc.

We did a wrapper NPM module around this module where we could implement our chaining if needed. So, if we need to change auth schema across all our deployments we simply update our NPM module and redeploy our services. Voila!

However, @AdriVanHoudt your situation could be different.

That's how we do it:
```js
      const credentials = {
        token,
        id: user.id,
        username: user.name,
        scope: false
      };
      const artefacts = {
        user
      };

      callback(null, true, credentials, artefacts);
```

I have no strong opinion weather `hapi-auth-bearer-token` should support chaining or not.

**Comment by AdriVanHoudt** [comment]
This is a documented and handy feature, I don't see a problem relying on it. 
You stated that the second scheme relies on the first one? How so?

Our server expect credentials to be the user object atm so changing that is not something I plan on doing ;)

The question I had was more about the effect of setting artifacts and if hapi does something special with it (with or without chaining)

**Comment by johnbrett** [comment]
@AdriVanHoudt nice work, I left some feedback on the PR. I think it's a documented feature of the framework so happy for this plugin to support it. 

I do think it's bad practice for a second auth scheme to depend on the first also, but I don't think that's what users will use chaining for.

**Comment by AdriVanHoudt** [comment]
Yeah they should not depend on each other and if artifacts do this then that would not be a solution

**Comment by johnbrett** [comment]
This was fixed with https://github.com/johnbrett/hapi-auth-bearer-token/pull/89. Great work @AdriVanHoudt, and good catch on checking for multiple strategies for route as well!

**Comment by AdriVanHoudt** [comment]
@johnbrett was my pleasure! And this works out better than what I had on hapi-auth-bearer-simple 🔥 oss ftw
