### ISSUE TITLE
Use joi schema to validate the authentication options.

### ISSUE THREAD

**Issue by johnbrett** [johnbrett/hapi-auth-bearer-token#99]
`github.com/hapijs/joi` makes schemas much more readable, easier to test and reduce the likelihood of unintended bugs. 

When this module was first written, it had one or two options, meaning it didn't really need a joi schema. This has since grown and it would now be worth adding a `joi` schema and validate this when registering an auth method. 

Note: This doesn't add any performance hit per request, only on auth scheme registration, as the auth schema will only be validated when schema is registered.

*This issue for new contributors, myself and @AdriVanHoudt are available to help work through this PR*

**Comment by AdriVanHoudt** [comment]
I can also help new contributors!

**Comment by jonathansamines** [comment]
Hey @johnbrett I´d like to help working with this one! I´ll PR later with this change

**Comment by johnbrett** [comment]
Closed via https://github.com/johnbrett/hapi-auth-bearer-token/issues/101
